/*
 * This source file was generated by the Gradle 'init' task
 */
package com.healthtracker;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ApiHealthTrackerApplicationTest {
    //@Test
    void appHasAGreeting() {
        ApiHealthTrackerApplication classUnderTest = new ApiHealthTrackerApplication();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
